stages:
- build
- test

build:tests:
    stage: build
    image: composer
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
        - vendor/
    script:
    - eval $(ssh-agent -s)
    - sh tools/setup-ssh.sh
    - sh tools/composer-install.sh ${JENKINS_GITHUB_PERSONAL_TOKEN}
    artifacts:
        paths:
        - vendor/
        expire_in: 1 day

test:unit:
    stage: test
    image: php:7.1-cli-alpine
    dependencies:
    - build:tests
    script:
    - php vendor/bin/phpunit --bootstrap vendor/autoload.php tests 
